# Generated by Django 2.2.3 on 2019-08-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190805_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='profile',
        ),
    ]
